-- Seeds para Categories
-- Gerado automaticamente

INSERT INTO categories (name) VALUES
  ('Adjustable Difficulty'),
  ('Adjustable Text Size'),
  ('Camera Comfort'),
  ('Captions available'),
  ('Chat Speech-to-text'),
  ('Chat Text-to-speech'),
  ('Co-op'),
  ('Color Alternatives'),
  ('Commentary available'),
  ('Cross-Platform Multiplayer'),
  ('Custom Volume Controls'),
  ('Family Sharing'),
  ('Full controller support'),
  ('Game demo'),
  ('HDR available'),
  ('In-App Purchases'),
  ('Includes Source SDK'),
  ('Includes level editor'),
  ('Keyboard Only Option'),
  ('LAN Co-op'),
  ('LAN PvP'),
  ('MMO'),
  ('Mouse Only Option'),
  ('Multi-player'),
  ('Narrated Game Menus'),
  ('Online Co-op'),
  ('Online PvP'),
  ('Partial Controller Support'),
  ('Playable without Timed Input'),
  ('PvP'),
  ('Remote Play Together'),
  ('Remote Play on Phone'),
  ('Remote Play on TV'),
  ('Remote Play on Tablet'),
  ('Save Anytime'),
  ('Shared/Split Screen'),
  ('Shared/Split Screen Co-op'),
  ('Shared/Split Screen PvP'),
  ('Single-player'),
  ('Stats'),
  ('Steam Achievements'),
  ('Steam Cloud'),
  ('Steam Leaderboards'),
  ('Steam Timeline'),
  ('Steam Trading Cards'),
  ('Steam Turn Notifications'),
  ('Steam Workshop'),
  ('SteamVR Collectibles'),
  ('Stereo Sound'),
  ('Subtitle Options'),
  ('Surround Sound'),
  ('Tracked Controller Support'),
  ('VR Supported'),
  ('Valve Anti-Cheat enabled');

-- Total: 54 categorias
