-- Seeds para Developers
-- Gerado automaticamente

INSERT INTO developers (name) VALUES
  ('24 Entertainment'),
  ('Activision Shanghai'),
  ('AdHoc Studio'),
  ('Amazon Games'),
  ('Arrowhead Game Studios'),
  ('Aspyr (Linux)'),
  ('Aspyr (Mac)'),
  ('Avalanche Software'),
  ('Battlefield Studios'),
  ('BeamNG'),
  ('Beenox'),
  ('Behaviour Interactive Inc.'),
  ('Bethesda Game Studios'),
  ('Blizzard Entertainment, Inc.'),
  ('Blue Mammoth Games'),
  ('Bohemia Interactive'),
  ('CAPCOM Co., Ltd.'),
  ('CD PROJEKT RED'),
  ('CREATIVE ASSEMBLY'),
  ('CaptureAge'),
  ('CenterPoint Gaming'),
  ('Chief Rebel'),
  ('Coffee Stain Studios'),
  ('Colossal Order Ltd.'),
  ('ConcernedApe'),
  ('Crytek'),
  ('Cygames, Inc.'),
  ('Demonware'),
  ('Digital Extremes'),
  ('Dirty Adventures 🖤'),
  ('EA Canada'),
  ('EA Romania'),
  ('Edmund McMillen'),
  ('Embark Studios'),
  ('Facepunch Studios'),
  ('Fair Games ApS'),
  ('Fancy Games'),
  ('Feral Interactive'),
  ('Firaxis Games'),
  ('Forgotten Empires'),
  ('FromSoftware, Inc.'),
  ('Full Circle'),
  ('GIANTS Software'),
  ('Gaijin Entertainment'),
  ('Gearbox Software'),
  ('Grinding Gear Games'),
  ('Half Sword Games'),
  ('Hello Games'),
  ('High Moon Studios'),
  ('Infinity Ward'),
  ('Iron Gate AB'),
  ('Julius Krüger'),
  ('KONAMI'),
  ('KURO GAMES'),
  ('Kenny Sun'),
  ('Kinetic Games'),
  ('Kunos Simulazioni'),
  ('Larian Studios'),
  ('Leppsoft'),
  ('LocalThunk'),
  ('Ludeon Studios'),
  ('Marcel Zurawka'),
  ('Maxis'),
  ('Mega Crit'),
  ('Morefun Studios'),
  ('NetEase Games'),
  ('Nicalis, Inc.'),
  ('Ninja Kiwi'),
  ('Nuggets Entertainment'),
  ('OBS Project'),
  ('Obsidian Entertainment'),
  ('PUBG Corporation'),
  ('Paradox Development Studio'),
  ('Platypus Entertainment'),
  ('Playground Games'),
  ('Pocketpair'),
  ('ProjectMoon'),
  ('Psyonix LLC'),
  ('Ramjet Studios'),
  ('Raven Software'),
  ('Re-Logic'),
  ('Red Barrels'),
  ('Respawn'),
  ('Respawn Entertainment'),
  ('RobTop Games'),
  ('Rockstar Games'),
  ('Rockstar North'),
  ('SCS Software'),
  ('Saber Interactive'),
  ('Skybound Games'),
  ('Sledgehammer Games'),
  ('Statespace'),
  ('Supergiant Games'),
  ('TML Team'),
  ('TaleWorlds Entertainment'),
  ('Tantalus Media'),
  ('Team Cherry'),
  ('Team Jade'),
  ('Team PEAK'),
  ('Team Soda'),
  ('The Fun Pimps'),
  ('The Indie Stone'),
  ('Toys for Bob'),
  ('Treyarch'),
  ('Ubisoft Montreal'),
  ('VRChat Inc.'),
  ('Valve'),
  ('Wallpaper Engine Team'),
  ('Wicked Witch'),
  ('World''s Edge'),
  ('semiwork'),
  ('vedinad');

-- Total: 112 desenvolvedores
