-- Seeds para Publishers
-- Gerado automaticamente

INSERT INTO publishers (name) VALUES
  ('2K'),
  ('Activision'),
  ('Activision (Excluding Japan and Asia)'),
  ('AdHoc Studio'),
  ('Aggro Crab'),
  ('Amazon Games'),
  ('Arc Games'),
  ('Aspyr (Linux)'),
  ('Aspyr (Mac)'),
  ('Bandai Namco Entertainment'),
  ('BeamNG'),
  ('Behaviour Interactive Inc.'),
  ('Bethesda Softworks'),
  ('Blizzard Entertainment, Inc.'),
  ('Bohemia Interactive'),
  ('CAPCOM Co., Ltd.'),
  ('CD PROJEKT RED'),
  ('CenterPoint Gaming'),
  ('Coffee Stain Publishing'),
  ('ConcernedApe'),
  ('Crytek'),
  ('Cygames, Inc.'),
  ('Devolver Digital'),
  ('Digital Extremes'),
  ('Dirty Adventures 🖤'),
  ('Electronic Arts'),
  ('Embark Studios'),
  ('Facepunch Studios'),
  ('Fair Games ApS'),
  ('Feral Interactive'),
  ('Focus Entertainment'),
  ('FromSoftware, Inc.'),
  ('FromSoftware, Inc. (Japan)'),
  ('GIANTS Software'),
  ('Gaijin Network Ltd'),
  ('Game Seer Publishing'),
  ('Grinding Gear Games'),
  ('Hello Games'),
  ('Irox Games'),
  ('KONAMI'),
  ('KRAFTON, Inc.'),
  ('KURO GAMES'),
  ('Kinetic Games'),
  ('Kunos Simulazioni'),
  ('Landfall'),
  ('Larian Studios'),
  ('Leppsoft'),
  ('Ludeon Studios'),
  ('Mega Crit'),
  ('Morefun Studios'),
  ('NetEase Games'),
  ('NetEase Games Global'),
  ('Nicalis, Inc.'),
  ('Ninja Kiwi'),
  ('Nuggets Entertainment'),
  ('OBS Project'),
  ('Paradox Interactive'),
  ('PlayStation Publishing LLC'),
  ('Playstack'),
  ('Pocketpair'),
  ('ProjectMoon'),
  ('Psyonix LLC'),
  ('Ramjet Studios'),
  ('Re-Logic'),
  ('Red Barrels'),
  ('RobTop Games'),
  ('Rockstar Games'),
  ('SCS Software'),
  ('SEGA'),
  ('Secret Mode'),
  ('Skybound Games'),
  ('Statespace'),
  ('Supergiant Games'),
  ('TML Team'),
  ('TaleWorlds Entertainment'),
  ('Team Cherry'),
  ('The Fun Pimps Entertainment LLC'),
  ('The Indie Stone'),
  ('TiMi Studio Group'),
  ('Ubisoft'),
  ('VRChat Inc.'),
  ('Valve'),
  ('Wallpaper Engine Team'),
  ('Warner Bros. Games'),
  ('Xbox Game Studios'),
  ('Ytopia'),
  ('bilibili'),
  ('semiwork'),
  ('vedinad'),
  ('方块游戏 (Asia)');

-- Total: 90 publishers
